name: PubMed Monitoring

on:
  schedule:
    - cron: '0 13 * * *' # 毎日アメリカ中央時間の7時
  workflow_dispatch:

jobs:
  run-notebook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install nbconvert requests openpyxl

      - name: Execute Notebook
        env: # 環境変数を設定
          PUBMED_API_KEY: ${{ secrets.PUBMED_API_KEY }}
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
          RECIPIENT: ${{ secrets.RECIPIENT }}
        run: |
          jupyter nbconvert --to notebook --execute PubMed_Monitoring.ipynb --ExecutePreprocessor.kernel_name=python
