name: PubMed Monitoring

on:
  workflow_dispatch:  # 手動実行を有効化
  schedule:           # 定期実行を設定
    - cron: '0 13 * * *'  # 毎日アメリカ中央時間の午前7時（UTCで午後1時）

jobs:
  run-notebook:
    runs-on: ubuntu-latest

    steps:
      # リポジトリのチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v3

      # Python環境のセットアップ
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      # 必要なパッケージをインストール
      - name: Install dependencies
        run: |
          pip install nbconvert requests openpyxl

      # Jupyter Notebookの実行
      - name: Execute Notebook
        run: |
          jupyter nbconvert --to notebook --execute PubMed_Monitoring.ipynb --ExecutePreprocessor.kernel_name=python3
