name: Run PubMed Monitoring

on:
  schedule:
    - cron: "0 13 * * *"  # 毎日UTCの13時に実行 (CSTの7時)
  workflow_dispatch:

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: pip install openpyxl requests smtplib

      - name: Execute PubMed Monitoring
        run: python pubmed_monitoring.py
